# Generated by Django 4.1 on 2023-01-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NaverMovie",
            fields=[
                ("column1", models.IntegerField(blank=True, null=True)),
                ("moviecode", models.IntegerField(primary_key=True, serialize=False)),
                ("moviename", models.CharField(blank=True, max_length=50, null=True)),
                ("genre", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("timeline", models.CharField(blank=True, max_length=50, null=True)),
                ("openingdate", models.DateField(blank=True, null=True)),
                ("valuation", models.FloatField(blank=True, null=True)),
                ("director", models.CharField(blank=True, max_length=50, null=True)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("actors", models.CharField(blank=True, max_length=50, null=True)),
                ("heartcount", models.IntegerField(blank=True, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StarComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column1", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("sctime", models.DateTimeField(auto_now_add=True, null=True)),
                ("starscore", models.IntegerField(blank=True, null=True)),
                ("recomm", models.IntegerField(blank=True, null=True)),
                ("unrecomm", models.IntegerField(blank=True, null=True)),
                ("nicknid", models.TextField(blank=True, null=True)),
                ("userid", models.CharField(blank=True, max_length=50, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                (
                    "moviecode",
                    models.ForeignKey(
                        blank=True,
                        db_column="moviecode",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="board.navermovie",
                    ),
                ),
            ],
        ),
    ]
