# Generated by Django 4.1 on 2023-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="navermovie",
            name="wc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
