# Generated by Django 4.1 on 2023-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_navermovie_wc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starcomments",
            name="recomm",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="starcomments",
            name="unrecomm",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
